data = [
    {
        'County': 'Autauga',
        'Antlered Public Land': 42,
        'Antlered Private Land': 1376,
        'Antlered Unk. Land': 0,
        'Antlered Total': 1418,
        'Unantlered Public Land': 44,
        'Unantlered Private Land': 1311,
        'Unantlered Unk. Land': 0,
        'Unantlered Total': 1355,
        'Total': 2773,
        'Longitude': 86.6441,
        'Latitude': 32.5364
    },
    {
        'County': 'Baldwin',
        'Antlered Public Land': 138,
        'Antlered Private Land': 2570,
        'Antlered Unk. Land': 0,
        'Antlered Total': 2708,
        'Unantlered Public Land': 57,
        'Unantlered Private Land': 2886,
        'Unantlered Unk. Land': 0,
        'Unantlered Total': 2943,
        'Total': 5651,
        'Longitude': 87.7763,
        'Latitude': 30.6014
    },
    {
        'County': 'Barbour',
        'Antlered Public Land': 236,
        'Antlered Private Land': 1922,
        'Antlered Unk. Land': 0,
        'Antlered Total': 2158,
        'Unantlered Public Land': 280,
        'Unantlered Private Land': 1800,
        'Unantlered Unk. Land': 0,
        'Unantlered Total': 2080,
        'Total': 4238,
        'Longitude': 85.3932,
        'Latitude': 31.8694
    },
    {
        'County': 'Bibb',
        'Antlered Public Land': 255,
        'Antlered Private Land': 1532,
        'Antlered Unk. Land': 0,
        'Antlered Total': 1787,
        'Unantlered Public Land': 164,
        'Unantlered Private Land': 1440,
        'Unantlered Unk. Land': 0,
        'Unantlered Total': 1604,
        'Total': 3391,
        'Longitude': 87.1265,
        'Latitude': 33.0225
    },
    {
        'County': 'Blount',
        'Antlered Public Land': 6,
        'Antlered Private Land': 1157,
        'Antlered Unk. Land': 0,
        'Antlered Total': 1163,
        'Unantlered Public Land': 5,
        'Unantlered Private Land': 684,
        'Unantlered Unk. Land': 0,
        'Unantlered Total': 689,
        'Total': 1852,
        'Longitude': 86.5679,
        'Latitude': 33.9821
    },
    {
        'County': 'Bullock',
        'Antlered Public Land': 17,
        'Antlered Private Land': 1813,
        'Antlered Unk. Land': 0,
        'Antlered Total': 1830,
        'Unantlered Public Land': 13,
        'Unantlered Private Land': 2129,
        'Unantlered Unk. Land': 0,
        'Unantlered Total': 2142,
        'Total': 3972,
        'Longitude': 85.7129,
        'Latitude': 32.1034
    },
    {
        "County": "Butler",
        "Antlered Public Land": 20,
        "Antlered Private Land": 1828,
        "Antlered Unk. Land": 0,
        "Antlered Total": 1848,
        "Unantlered Public Land": 34,
        "Unantlered Private Land": 1615,
        "Unantlered Unk. Land": 0,
        "Unantlered Total": 1649,
        "Total": 3497,
        "Longitude": 86.6803,
        "Latitude": 31.7532
    },
    {
        "County": "Calhoun",
        "Antlered Public Land": 140,
        "Antlered Private Land": 980,
        "Antlered Unk. Land": 0,
        "Antlered Total": 1120,
        "Unantlered Public Land": 166,
        "Unantlered Private Land": 661,
        "Unantlered Unk. Land": 0,
        "Unantlered Total": 827,
        "Total": 1947,
        "Longitude": 85.8225,
        "Latitude": 33.7406
    },
    {
        "County": "Chambers",
        "Antlered Public Land": 11,
        "Antlered Private Land": 1093,
        "Antlered Unk. Land": 0,
        "Antlered Total": 1104,
        "Unantlered Public Land": 5,
        "Unantlered Private Land": 920,
        "Unantlered Unk. Land": 0,
        "Unantlered Total": 925,
        "Total": 2029,
        "Longitude": 85.3906,
        "Latitude": 32.9106
    },
    {
        "County": "Cherokee",
        "Antlered Public Land": 26,
        "Antlered Private Land": 1496,
        "Antlered Unk. Land": 0,
        "Antlered Total": 1522,
        "Unantlered Public Land": 32,
        "Unantlered Private Land": 1403,
        "Unantlered Unk. Land": 0,
        "Unantlered Total": 1435,
        "Total": 2957,
        "Longitude": 85.6069,
        "Latitude": 34.1675
    },
    {
        "County": "Chilton",
        "Antlered Public Land": 58,
        "Antlered Private Land": 1617,
        "Antlered Unk. Land": 0,
        "Antlered Total": 1675,
        "Unantlered Public Land": 41,
        "Unantlered Private Land": 1522,
        "Unantlered Unk. Land": 0,
        "Unantlered Total": 1563,
        "Total": 3238,
        "Longitude": 86.718,
        "Latitude": 32.8359
    },
    {
        "County": "Choctaw", 
        "Antlered Public Land": 14, 
        "Antlered Private Land": 1406, 
        "Antlered Unk. Land": 0, 
        "Antlered Total": 1420, 
        "Unantlered Public Land": 13, 
        "Unantlered Private Land": 1221, 
        "Unantlered Unk. Land": 0, 
        "Unantlered Total": 1234, 
        "Total": 2654, 
        "Longitude": 88.2278, 
        "Latitude": 32.0105
    },
    {
        "County": "Clarke", 
        "Antlered Public Land": 48, 
        "Antlered Private Land": 2386, 
        "Antlered Unk. Land": 0, 
        "Antlered Total": 2434, 
        "Unantlered Public Land": 40, 
        "Unantlered Private Land": 2066, 
        "Unantlered Unk. Land": 0, 
        "Unantlered Total": 2106, 
        "Total": 4540, 
        "Longitude": 87.8304, 
        "Latitude": 31.6826
    },
    {
        'County': 'Clay',
        'Antlered Public Land': 74,
        'Antlered Private Land': 1027,
        'Antlered Unk. Land': 0,
        'Antlered Total': 1101,
        'Unantlered Public Land': 23,
        'Unantlered Private Land': 752,
        'Unantlered Unk. Land': 0,
        'Unantlered Total': 775,
        'Total': 1876,
        'Longitude': 85.8644,
        'Latitude': 33.2716
    },
    {
        'County': 'Cleburne',
        'Antlered Public Land': 151,
        'Antlered Private Land': 525,
        'Antlered Unk. Land': 0,
        'Antlered Total': 676,
        'Unantlered Public Land': 48,
        'Unantlered Private Land': 418,
        'Unantlered Unk. Land': 0,
        'Unantlered Total': 466,
        'Total': 1142,
        'Longitude': 85.52,
        'Latitude': 33.6747
    },
    {
        'County': 'Coffee',
        'Antlered Public Land': 43,
        'Antlered Private Land': 1148,
        'Antlered Unk. Land': 0,
        'Antlered Total': 1191,
        'Unantlered Public Land': 22,
        'Unantlered Private Land': 868,
        'Unantlered Unk. Land': 0,
        'Unantlered Total': 890,
        'Total': 2081,
        'Longitude': 85.9892,
        'Latitude': 31.4011
    },
    {
        'County': 'Colbert',
        'Antlered Public Land': 106,
        'Antlered Private Land': 847,
        'Antlered Unk. Land': 0,
        'Antlered Total': 953,
        'Unantlered Public Land': 98,
        'Unantlered Private Land': 704,
        'Unantlered Unk. Land': 0,
        'Unantlered Total': 802,
        'Total': 1755,
        'Longitude': 87.8047,
        'Latitude': 34.7118
    },
    {
        'County': 'Conecuh',
        'Antlered Public Land': 48,
        'Antlered Private Land': 1345,
        'Antlered Unk. Land': 0,
        'Antlered Total': 1393,
        'Unantlered Public Land': 24,
        'Unantlered Private Land': 1525,
        'Unantlered Unk. Land': 0,
        'Unantlered Total': 1549,
        'Total': 2942,
        'Longitude': 86.9942,
        'Latitude': 31.4327
    },
    {
        "County": "Coosa",
        "Antlered Public Land": 62,
        "Antlered Private Land": 1569,
        "Antlered Unk. Land": 0,
        "Antlered Total": 1631,
        "Unantlered Public Land": 21,
        "Unantlered Private Land": 1421,
        "Unantlered Unk. Land": 0,
        "Unantlered Total": 1442,
        "Total": 3073,
        "Longitude": 86.242,
        "Latitude": 32.9364,
    },
    {
        "County": "Covington",
        "Antlered Public Land": 196,
        "Antlered Private Land": 1585,
        "Antlered Unk. Land": 0,
        "Antlered Total": 1781,
        "Unantlered Public Land": 112,
        "Unantlered Private Land": 1611,
        "Unantlered Unk. Land": 0,
        "Unantlered Total": 1723,
        "Total": 3504,
        "Longitude": 86.4486,
        "Latitude": 31.2536,
    },
    {
        "County": "Crenshaw",
        "Antlered Public Land": 4,
        "Antlered Private Land": 1592,
        "Antlered Unk. Land": 0,
        "Antlered Total": 1596,
        "Unantlered Public Land": 8,
        "Unantlered Private Land": 1450,
        "Unantlered Unk. Land": 0,
        "Unantlered Total": 1458,
        "Total": 3054,
        "Longitude": 86.3119,
        "Latitude": 31.7297
    },
    {
        "County": "Cullman",
        "Antlered Public Land": 6,
        "Antlered Private Land": 1178,
        "Antlered Unk. Land": 0,
        "Antlered Total": 1184,
        "Unantlered Public Land": 1,
        "Unantlered Private Land": 701,
        "Unantlered Unk. Land": 0,
        "Unantlered Total": 702,
        "Total": 1886,
        "Longitude": 86.8698,
        "Latitude": 34.1301
    },
    {
        "County": "Dale",
        "Antlered Public Land": 91,
        "Antlered Private Land": 906,
        "Antlered Unk. Land": 0,
        "Antlered Total": 997,
        "Unantlered Public Land": 69,
        "Unantlered Private Land": 634,
        "Unantlered Unk. Land": 0,
        "Unantlered Total": 703,
        "Total": 1700,
        "Longitude": 85.6094,
        "Latitude": 31.4069
    },
    {
        "County": "Dallas",
        "Antlered Public Land": 76,
        "Antlered Private Land": 2011,
        "Antlered Unk. Land": 0,
        "Antlered Total": 2087,
        "Unantlered Public Land": 140,
        "Unantlered Private Land": 2445,
        "Unantlered Unk. Land": 0,
        "Unantlered Total": 2585,
        "Total": 4672,
        "Longitude": 87.056,
        "Latitude": 32.4074
    },
    {
        "County": "Dekalb",
        "Antlered Public Land": 14,
        "Antlered Private Land": 1543,
        "Antlered Unk. Land": 0,
        "Antlered Total": 1557,
        "Unantlered Public Land": 20,
        "Unantlered Private Land": 1185,
        "Unantlered Unk. Land": 0,
        "Unantlered Total": 1205,
        "Total": 2762,
        "Longitude": 85.8072,
        "Latitude": 34.4555
    },
    {
        "County": "Elmore",
        "Antlered Public Land": 26,
        "Antlered Private Land": 1253,
        "Antlered Unk. Land": 0,
        "Antlered Total": 1279,
        "Unantlered Public Land": 7,
        "Unantlered Private Land": 994,
        "Unantlered Unk. Land": 0,
        "Unantlered Total": 1001,
        "Total": 2280,
        "Longitude": 86.1521,
        "Latitude": 32.5979
    },
    {
        "County": "Escambia",
        "Antlered Public Land": 81,
        "Antlered Private Land": 1211,
        "Antlered Unk. Land": 0,
        "Antlered Total": 1292,
        "Unantlered Public Land": 82,
        "Unantlered Private Land": 1244,
        "Unantlered Unk. Land": 0,
        "Unantlered Total": 1326,
        "Total": 2618,
        "Longitude": 87.1619,
        "Latitude": 31.1394
    },
    {
        "County": "Etowah",
        "Antlered Public Land": 8,
        "Antlered Private Land": 1052,
        "Antlered Unk. Land": 0,
        "Antlered Total": 1060,
        "Unantlered Public Land": 3,
        "Unantlered Private Land": 592,
        "Unantlered Unk. Land": 0,
        "Unantlered Total": 595,
        "Total": 1655,
        "Longitude": 86.0401,
        "Latitude": 34.0451
    },
    {
        "County": "Fayette",
        "Antlered Public Land": 3,
        "Antlered Private Land": 1582,
        "Antlered Unk. Land": 0,
        "Antlered Total": 1585,
        "Unantlered Public Land": 8,
        "Unantlered Private Land": 1812,
        "Unantlered Unk. Land": 0,
        "Unantlered Total": 1820,
        "Total": 3405,
        "Longitude": 87.7383,
        "Latitude": 33.7194,
    },
    {
        "County": "Franklin",
        "Antlered Public Land": 15,
        "Antlered Private Land": 1519,
        "Antlered Unk. Land": 0,
        "Antlered Total": 1534,
        "Unantlered Public Land": 40,
        "Unantlered Private Land": 1504,
        "Unantlered Unk. Land": 0,
        "Unantlered Total": 1544,
        "Total": 3078,
        "Longitude": 87.8439,
        "Latitude": 34.4437,
    },
    {
        "County": "Geneva",
        "Antlered Public Land": 38,
        "Antlered Private Land": 867,
        "Antlered Unk. Land": 0,
        "Antlered Total": 905,
        "Unantlered Public Land": 50,
        "Unantlered Private Land": 656,
        "Unantlered Unk. Land": 0,
        "Unantlered Total": 706,
        "Total": 1611,
        "Longitude": 85.8342,
        "Latitude": 31.0678,
    },
    {
        "County": "Greene",
        "Antlered Public Land": 53,
        "Antlered Private Land": 1233,
        "Antlered Unk. Land": 0,
        "Antlered Total": 1286,
        "Unantlered Public Land": 43,
        "Unantlered Private Land": 1388,
        "Unantlered Unk. Land": 0,
        "Unantlered Total": 1431,
        "Total": 2717,
        "Longitude": 87.9567,
        "Latitude": 32.8537,
    },
    {
        "County": "Hale",
        "Antlered Public Land": 130,
        "Antlered Private Land": 856,
        "Antlered Unk. Land": 0,
        "Antlered Total": 986,
        "Unantlered Public Land": 74,
        "Unantlered Private Land": 926,
        "Unantlered Unk. Land": 0,
        "Unantlered Total": 1000,
        "Total": 1986,
        "Longitude": 87.6348,
        "Latitude": 32.7485,
    },
    {
        'County': 'Henry',
        'Antlered Public Land': 7,
        'Antlered Private Land': 1795,
        'Antlered Unk. Land': 0,
        'Antlered Total': 1802,
        'Unantlered Public Land': 10,
        'Unantlered Private Land': 1446,
        'Unantlered Unk. Land': 0,
        'Unantlered Total': 1456,
        'Total': 3258,
        'Longitude': 85.2189,
        'Latitude': 31.516
    },
    {
        'County': 'Houston',
        'Antlered Public Land': 1,
        'Antlered Private Land': 1238,
        'Antlered Unk. Land': 0,
        'Antlered Total': 1239,
        'Unantlered Public Land': 4,
        'Unantlered Private Land': 983,
        'Unantlered Unk. Land': 0,
        'Unantlered Total': 987,
        'Total': 2226,
        'Longitude': 85.3003,
        'Latitude': 31.1368
    },
        {'County': 'Jackson', 'Antlered Public Land': 287, 'Antlered Private Land': 2801, 'Antlered Unk. Land': 0, 'Antlered Total': 3088, 'Unantlered Public Land': 229, 'Unantlered Private Land': 2124, 'Unantlered Unk. Land': 0, 'Unantlered Total': 2353, 'Total': 5441, 'Longitude': 86.0006, 'Latitude': 34.7662},
        {'County': 'Jefferson', 'Antlered Public Land': 17, 'Antlered Private Land': 1581, 'Antlered Unk. Land': 0, 'Antlered Total': 1598, 'Unantlered Public Land': 7, 'Unantlered Private Land': 1181, 'Unantlered Unk. Land': 0, 'Unantlered Total': 1188, 'Total': 2786, 'Longitude': 86.8104, 'Latitude': 33.5186},
        {'County': 'Lamar', 'Antlered Public Land': 46, 'Antlered Private Land': 1523, 'Antlered Unk. Land': 0, 'Antlered Total': 1569, 'Unantlered Public Land': 62, 'Unantlered Private Land': 2020, 'Unantlered Unk. Land': 0, 'Unantlered Total': 2082, 'Total': 3651, 'Longitude': 88.096, 'Latitude': 33.7912},
        {'County': 'Lauderdale', 'Antlered Public Land': 111, 'Antlered Private Land': 1787, 'Antlered Unk. Land': 0, 'Antlered Total': 1898, 'Unantlered Public Land': 113, 'Unantlered Private Land': 1470, 'Unantlered Unk. Land': 0, 'Unantlered Total': 1583, 'Total': 3481, 'Longitude': 87.6563, 'Latitude': 34.8926},
        {'County': 'Lawrence', 'Antlered Public Land': 138, 'Antlered Private Land': 1047, 'Antlered Unk. Land': 0, 'Antlered Total': 1185, 'Unantlered Public Land': 78, 'Unantlered Private Land': 574, 'Unantlered Unk. Land': 0, 'Unantlered Total': 652, 'Total': 1837, 'Longitude': 87.3016, 'Latitude': 34.5481},
        {'County': 'Lee', 'Antlered Public Land': 7, 'Antlered Private Land': 1140, 'Antlered Unk. Land': 0, 'Antlered Total': 1147, 'Unantlered Public Land': 10, 'Unantlered Private Land': 1096, 'Unantlered Unk. Land': 0, 'Unantlered Total': 1106, 'Total': 2253, 'Longitude': 85.3486, 'Latitude': 32.6016},
        {
            "County": "Limestone",
            "Antlered Public Land": 65,
            "Antlered Private Land": 1250,
            "Antlered Unk. Land": 0,
            "Antlered Total": 1315,
            "Unantlered Public Land": 50,
            "Unantlered Private Land": 1054,
            "Unantlered Unk. Land": 0,
            "Unantlered Total": 1104,
            "Total": 2419,
            "Longitude": 86.9717,
            "Latitude": 34.8044
          },
          {
            "County": "Lowndes",
            "Antlered Public Land": 103,
            "Antlered Private Land": 1490,
            "Antlered Unk. Land": 0,
            "Antlered Total": 1593,
            "Unantlered Public Land": 68,
            "Unantlered Private Land": 1319,
            "Unantlered Unk. Land": 0,
            "Unantlered Total": 1387,
            "Total": 2980,
            "Longitude": 86.6517,
            "Latitude": 32.2127
          },
          {
            "County": "Macon",
            "Antlered Public Land": 75,
            "Antlered Private Land": 1252,
            "Antlered Unk. Land": 0,
            "Antlered Total": 1327,
            "Unantlered Public Land": 32,
            "Unantlered Private Land": 1429,
            "Unantlered Unk. Land": 0,
            "Unantlered Total": 1461,
            "Total": 2788,
            "Longitude": 85.6924,
            "Latitude": 32.3901
          },
          {
            "County": "Madison",
            "Antlered Public Land": 107,
            "Antlered Private Land": 1682,
            "Antlered Unk. Land": 0,
            "Antlered Total": 1789,
            "Unantlered Public Land": 67,
            "Unantlered Private Land": 1276,
            "Unantlered Unk. Land": 0,
            "Unantlered Total": 1343,
            "Total": 3132,
            "Longitude": 86.5229,
            "Latitude": 34.7339
          },
          {
            "County": "Marengo",
            "Antlered Public Land": 22,
            "Antlered Private Land": 1605,
            "Antlered Unk. Land": 0,
            "Antlered Total": 1627,
            "Unantlered Public Land": 20,
            "Unantlered Private Land": 1481,
            "Unantlered Unk. Land": 0,
            "Unantlered Total": 1501,
            "Total": 3128,
            "Longitude": 87.7954,
            "Latitude": 32.2736
          },
          {
            "County": "Marion",
            "Antlered Public Land": 72,
            "Antlered Private Land": 1836,
            "Antlered Unk. Land": 0,
            "Antlered Total": 1908,
            "Unantlered Public Land": 71,
            "Unantlered Private Land": 1935,
            "Unantlered Unk. Land": 0,
            "Unantlered Total": 2006,
            "Total": 3914,
            "Longitude": 87.8505,
            "Latitude": 34.1439
        },
        {
            "County": "Marshall",
            "Antlered Public Land": 54,
            "Antlered Private Land": 801,
            "Antlered Unk. Land": 0,
            "Antlered Total": 855,
            "Unantlered Public Land": 33,
            "Unantlered Private Land": 386,
            "Unantlered Unk. Land": 0,
            "Unantlered Total": 419,
            "Total": 1274,
            "Longitude": 86.3077,
            "Latitude": 34.3676
        },
        {
            "County": "Mobile",
            "Antlered Public Land": 41,
            "Antlered Private Land": 1245,
            "Antlered Unk. Land": 0,
            "Antlered Total": 1286,
            "Unantlered Public Land": 19,
            "Unantlered Private Land": 1371,
            "Unantlered Unk. Land": 0,
            "Unantlered Total": 1390,
            "Total": 2676,
            "Longitude": 88.2216,
            "Latitude": 30.7276
        },
        {
            "County": "Monroe",
            "Antlered Public Land": 54,
            "Antlered Private Land": 1551,
            "Antlered Unk. Land": 0,
            "Antlered Total": 1605,
            "Unantlered Public Land": 28,
            "Unantlered Private Land": 1643,
            "Unantlered Unk. Land": 0,
            "Unantlered Total": 1671,
            "Total": 3276,
            "Longitude": 87.3343,
            "Latitude": 31.5486
        },
        {
            "County": "Montgomery",
            "Antlered Public Land": 5,
            "Antlered Private Land": 1682,
            "Antlered Unk. Land": 0,
            "Antlered Total": 1687,
            "Unantlered Public Land": 5,
            "Unantlered Private Land": 1696,
            "Unantlered Unk. Land": 0,
            "Unantlered Total": 1701,
            "Total": 3388,
            "Longitude": 86.2553,
            "Latitude": 32.214
        },
        {
            "County": "Morgan",
            "Antlered Public Land": 56,
            "Antlered Private Land": 815,
            "Antlered Unk. Land": 0,
            "Antlered Total": 871,
            "Unantlered Public Land": 65,
            "Unantlered Private Land": 398,
            "Unantlered Unk. Land": 0,
            "Unantlered Total": 463,
            "Total": 1334,
            "Longitude": 86.8835,
            "Latitude": 34.4557
        },
        {
            "County": "Perry",
            "Antlered Public Land": 50,
            "Antlered Private Land": 1357,
            "Antlered Unk. Land": 0,
            "Antlered Total": 1407,
            "Unantlered Public Land": 36,
            "Unantlered Private Land": 1549,
            "Unantlered Unk. Land": 0,
            "Unantlered Total": 1585,
            "Total": 2992,
            "Longitude": 87.3084,
            "Latitude": 32.6273
        },
        {
            "County": "Pickens",
            "Antlered Public Land": 43,
            "Antlered Private Land": 1691,
            "Antlered Unk. Land": 0,
            "Antlered Total": 1734,
            "Unantlered Public Land": 22,
            "Unantlered Private Land": 2166,
            "Unantlered Unk. Land": 0,
            "Unantlered Total": 2188,
            "Total": 3922,
            "Longitude": 88.0977,
            "Latitude": 33.2907
            },
            {
            "County": "Pike",
            "Antlered Public Land": 4,
            "Antlered Private Land": 1537,
            "Antlered Unk. Land": 0,
            "Antlered Total": 1541,
            "Unantlered Public Land": 2,
            "Unantlered Private Land": 1217,
            "Unantlered Unk. Land": 0,
            "Unantlered Total": 1219,
            "Total": 2760,
            "Longitude": 85.9423,
            "Latitude": 31.8136
            },
            {
                "County": "Randolph",
                "Antlered Public Land": 2,
                "Antlered Private Land": 1059,
                "Antlered Unk. Land": 0,
                "Antlered Total": 1061,
                "Unantlered Public Land": 3,
                "Unantlered Private Land": 807,
                "Unantlered Unk. Land": 0,
                "Unantlered Total": 810,
                "Total": 1871,
                "Longitude": 85.4577,
                "Latitude": 33.3001
            },
            {
                "County": "Russell",
                "Antlered Public Land": 88,
                "Antlered Private Land": 1908,
                "Antlered Unk. Land": 0,
                "Antlered Total": 1996,
                "Unantlered Public Land": 100,
                "Unantlered Private Land": 1912,
                "Unantlered Unk. Land": 0,
                "Unantlered Total": 2012,
                "Total": 4008,
                "Longitude": 85.1458,
                "Latitude": 32.282
            },
            {
                "County": "Shelby",
                "Antlered Public Land": 100,
                "Antlered Private Land": 1620,
                "Antlered Unk. Land": 0,
                "Antlered Total": 1720,
                "Unantlered Public Land": 55,
                "Unantlered Private Land": 1386,
                "Unantlered Unk. Land": 0,
                "Unantlered Total": 1441,
                "Total": 3161,
                "Longitude": 86.3102,
                "Latitude": 33.7109
            },
            {
                "County": "St.",
                "Antlered Public Land": 4,
                "Antlered Private Land": 1447,
                "Antlered Unk. Land": 0,
                "Antlered Total": 1451,
                "Unantlered Public Land": 1,
                "Unantlered Private Land": 1125,
                "Unantlered Unk. Land": 0,
                "Unantlered Total": 1126,
                "Total": 2577,
                "Longitude": 86.6844,
                "Latitude": 33.2678
            },
            {
                "County": "Sumter",
                "Antlered Public Land": 54,
                "Antlered Private Land": 1230,
                "Antlered Unk. Land": 0,
                "Antlered Total": 1284,
                "Unantlered Public Land": 29,
                "Unantlered Private Land": 1037,
                "Unantlered Unk. Land": 0,
                "Unantlered Total": 1066,
                "Total": 2350,
                "Longitude": 88.2065,
                "Latitude": 32.5905
            },
            {
                "County": "Talladega",
                "Antlered Public Land": 162,
                "Antlered Private Land": 1326,
                "Antlered Unk. Land": 0,
                "Antlered Total": 1488,
                "Unantlered Public Land": 51,
                "Unantlered Private Land": 966,
                "Unantlered Unk. Land": 0,
                "Unantlered Total": 1017,
                "Total": 2505,
                "Longitude": 86.1598,
                "Latitude": 33.4001
            },
            {
                "County": "Tallapoosa",
                "Antlered Public Land": 12,
                "Antlered Private Land": 1505,
                "Antlered Unk. Land": 0,
                "Antlered Total": 1517,
                "Unantlered Public Land": 7,
                "Unantlered Private Land": 1374,
                "Unantlered Unk. Land": 0,
                "Unantlered Total": 1381,
                "Total": 2898,
                "Longitude": 85.7912,
                "Latitude": 32.8582
            },
            {
                "County": "Tuscaloosa",
                "Antlered Public Land": 93,
                "Antlered Private Land": 2610,
                "Antlered Unk. Land": 0,
                "Antlered Total": 2703,
                "Unantlered Public Land": 74,
                "Unantlered Private Land": 2572,
                "Unantlered Unk. Land": 0,
                "Unantlered Total": 2646,
                "Total": 5349,
                "Longitude": 87.4531,
                "Latitude": 33.3056
            },
            {
                "County": "Walker",
                "Antlered Public Land": 45,
                "Antlered Private Land": 2249,
                "Antlered Unk. Land": 0,
                "Antlered Total": 2294,
                "Unantlered Public Land": 32,
                "Unantlered Private Land": 2102,
                "Unantlered Unk. Land": 0,
                "Unantlered Total": 2134,
                "Total": 4428,
                "Longitude": 87.3107,
                "Latitude": 33.788
            },
            {
                "County": "Washington",
                "Antlered Public Land": 13,
                "Antlered Private Land": 1486,
                "Antlered Unk. Land": 0,
                "Antlered Total": 1499,
                "Unantlered Public Land": 5,
                "Unantlered Private Land": 1414,
                "Unantlered Unk. Land": 0,
                "Unantlered Total": 1419,
                "Total": 2918,
                "Longitude": 88.2661,
                "Latitude": 31.4988
            },
            {
                "County": "Wilcox",
                "Antlered Public Land": 21,
                "Antlered Private Land": 1706,
                "Antlered Unk. Land": 0,
                "Antlered Total": 1727,
                "Unantlered Public Land": 20,
                "Unantlered Private Land": 1710,
                "Unantlered Unk. Land": 0,
                "Unantlered Total": 1730,
                "Total": 3457,
                "Longitude": 87.3001,
                "Latitude": 31.9923
            },
            {
                "County": "Winston",
                "Antlered Public Land": 212,
                "Antlered Private Land": 1282,
                "Antlered Unk. Land": 0,
                "Antlered Total": 1494,
                "Unantlered Public Land": 185,
                "Unantlered Private Land": 951,
                "Unantlered Unk. Land": 0,
                "Unantlered Total": 1136,
                "Total": 2630,
                "Longitude": 87.3942,
                "Latitude": 34.1503
            }         

]